//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.23 at 08:31:50 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://entity.shop", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, 
		xmlns= {@javax.xml.bind.annotation.XmlNs(prefix="e", namespaceURI = "http://entity.shop")})
package shop.entity;
