//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.14 at 10:48:01 AM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://order.nure.ua/entity/book/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ua.nure.order.entity.book;
