
package ua.nure.itech.jaxws.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ExchangeException", targetNamespace = "http://service.jaxws.itech.nure.ua/")
public class ExchangeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExchangeException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExchangeException_Exception(String message, ExchangeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ExchangeException_Exception(String message, ExchangeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ua.nure.itech.jaxws.service.ExchangeException
     */
    public ExchangeException getFaultInfo() {
        return faultInfo;
    }

}
