//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.08 at 06:26:19 PM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://order.nure.ua/entity/")
package ua.nure.order.entity;
