
package ua.nure.itech.jaxws.service.inheritance;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://inheritance.service.jaxws.itech.nure.ua/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:Hello")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloUser", targetNamespace = "http://inheritance.service.jaxws.itech.nure.ua/", className = "ua.nure.itech.jaxws.service.inheritance.HelloUser")
    @ResponseWrapper(localName = "helloUserResponse", targetNamespace = "http://inheritance.service.jaxws.itech.nure.ua/", className = "ua.nure.itech.jaxws.service.inheritance.HelloUserResponse")
    @Action(input = "urn:Hello", output = "http://inheritance.service.jaxws.itech.nure.ua/Hello/helloUserResponse")
    public String helloUser(
        @WebParam(name = "userName", targetNamespace = "")
        String userName);

}
