
package ua.nure.order.server.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Books", targetNamespace = "http://order.nure.ua/server/service", wsdlLocation = "file:/D:/Dev/wsps/luna/jaxwsBookServiceWebClient/books.wsdl")
public class Books
    extends Service
{

    private static final String ORDER_SERVICE_QNAME = "http://order.nure.ua/server/service";
	private static final URL BOOKS_WSDL_LOCATION;
    private static final WebServiceException BOOKS_EXCEPTION;
    private static final QName BOOKS_QNAME = new QName(ORDER_SERVICE_QNAME, "Books");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/books?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKS_WSDL_LOCATION = url;
        BOOKS_EXCEPTION = e;
    }

    public Books() {
        super(__getWsdlLocation(), BOOKS_QNAME);
    }

    public Books(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKS_QNAME, features);
    }

    public Books(URL wsdlLocation) {
        super(wsdlLocation, BOOKS_QNAME);
    }

    public Books(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKS_QNAME, features);
    }

    public Books(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Books(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookService
     */
    @WebEndpoint(name = "BookPort")
    public BookService getBookPort() {
        return super.getPort(new QName(ORDER_SERVICE_QNAME, "BookPort"), BookService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookService
     */
    @WebEndpoint(name = "BookPort")
    public BookService getBookPort(WebServiceFeature... features) {
        return super.getPort(new QName(ORDER_SERVICE_QNAME, "BookPort"), BookService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKS_EXCEPTION!= null) {
            throw BOOKS_EXCEPTION;
        }
        return BOOKS_WSDL_LOCATION;
    }

}
