
package ua.nure.itech.jaxws.service.handled;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://handled.service.jaxws.itech.nure.ua/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ua.nure.itech.jaxws.service.handled.ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param clientToken
     * @param parameters
     * @param serverToken
     * @return
     *     returns ua.nure.itech.jaxws.service.handled.HelloUserResponse
     * @throws ValidationException_Exception
     */
    @WebMethod(action = "urn:Hello")
    @WebResult(name = "helloUserResponse", targetNamespace = "http://handled.service.jaxws.itech.nure.ua/", partName = "result")
    @Action(input = "urn:Hello", output = "http://handled.service.jaxws.itech.nure.ua/Hello/helloUserResponse", fault = {
        @FaultAction(className = ValidationException_Exception.class, value = "http://handled.service.jaxws.itech.nure.ua/Hello/helloUser/Fault/ValidationException")
    })
    public HelloUserResponse helloUser(
        @WebParam(name = "helloUser", targetNamespace = "http://handled.service.jaxws.itech.nure.ua/", partName = "parameters")
        HelloUser parameters,
        @WebParam(name = "clientToken", targetNamespace = "http://handled.service.jaxws.itech.nure.ua/", header = true, partName = "clientToken")
        SecurityHeader clientToken,
        @WebParam(name = "serverToken", targetNamespace = "http://handled.service.jaxws.itech.nure.ua/", header = true, mode = WebParam.Mode.OUT, partName = "serverToken")
        Holder<SecurityHeader> serverToken)
        throws ValidationException_Exception
    ;

}
